---
title: "Democracy, Public Support, and Measurement Uncertainty: Appendix"
classoption: landscape
output:
  pdf_document:
    fig_caption: true
    latex_engine: xelatex
---

```{r setup, include=FALSE}
options(tinytex.verbose = TRUE)

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, eval = FALSE, dpi = 300)

if (!require(pacman)) install.packages("pacman")
library(pacman)

# load all the packages you will use below 
p_load(
  flextable, kableExtra, modelsummary, # tabulation
  latex2exp, # visualization
  broom, tidyverse, janitor, # data wrangling
  dotwhisker # visualization
) 

# Functions preload
set.seed(313)

# Theme setup
theme_set(theme_minimal())
```

\renewcommand{\thepage}{A\arabic{page}}


```{r tableAJPS, eval=TRUE}
load(here::here("output", "df_tables.rda"))

df_tableAJPS %>% 
  mutate(estimate = paste0(estimate, "\n ", conf),
         group = paste0(group, "\n (n: ", n, ")")) %>% 
  arrange(group, model) %>% 
  select(group, model, term, estimate) %>% 
  group_by(group) %>% 
  pivot_wider(names_from = model, values_from = estimate) %>% 
  mutate(term = str_replace_all(term, "\\n", " ")) %>% 
  arrange(group) %>% 
  flextable %>% 
  set_header_labels(group = "Model",
                    term = "Variable") %>% 
  merge_v(j = c("group")) %>% 
  hline(i = 8, border = officer::fp_border()) %>% 
  autofit() %>% 
  fit_to_width(8.5) %>% 
  set_caption("Estimates of Democratic Support on Democratic Institutions")

```


```{r table APSR, eval=TRUE}
df_tableAPSR %>% 
  mutate(estimate = paste0(estimate, "\n ", conf),
         group = paste0(group, "\n (n: ", n, ")")) %>% 
  arrange(group, model) %>% 
  select(group, model, term, estimate) %>% 
  group_by(group) %>% 
  pivot_wider(names_from = model, values_from = estimate) %>% 
  mutate(term = str_replace_all(term, "\\n", " ")) %>% 
  arrange(group) %>% 
  flextable %>% 
  set_header_labels(group = "Model",
                    term = "Variable") %>% 
  merge_v(j = c("group")) %>% 
  hline(i = 6, border = officer::fp_border()) %>% 
  autofit() %>% 
  fit_to_width(8.5) %>% 
  set_caption("Estimates of Democratic Institutions on Democratic Support")

```

