---
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: svm-latex-ms2.tex
title: "Democracy, Public Support, and Measurement Uncertainty"
subtitle: "Online Appendix"
# thanks: "Corresponding author: [yuehong-tai@uiowa.edu](mailto:yuehong-tai@uiowa.edu). Current version: `r format(Sys.time(), '%B %d, %Y')`."
author:
# - name: Yuehong 'Cassandra' Tai
#   affiliation: University of Iowa
# - name: Yue Hu
#   affiliation: Tsinghua University
# - name: Frederick Solt
#   affiliation: University of Iowa
abstract: ""
keywords: ""
date: "`r format(Sys.time(), '%B %d, %Y')`"
fontsize: 11pt
spacing: double
bibliography: \dummy{`r file.path(getwd(), list.files(getwd(), ".bib$", recursive = TRUE))`}
# csl: https://raw.githubusercontent.com/citation-style-language/styles/master/american-political-science-association.csl
biblio-style: apsr
citecolor: black
linkcolor: black
endnote: no
header-includes:
      - \usepackage{array}
      - \usepackage{caption}
      - \usepackage{graphicx}
      - \usepackage{siunitx}
      - \usepackage{colortbl}
      - \usepackage{multirow}
      - \usepackage{hhline}
      - \usepackage{calc}
      - \usepackage{tabularx}
      - \usepackage{threeparttable}
      - \usepackage{wrapfig}
nocite: |
  @Solt2020a
---

```{r setup, include=FALSE}
options(tinytex.verbose = TRUE)

knitr::opts_chunk$set(cache = TRUE, echo = FALSE, message = FALSE, warning = FALSE, dpi = 300, include = FALSE)

# If you haven't install `DCPOtools`
# remotes::install_github("fsolt/DCPOtools")

if (!require(pacman)) install.packages("pacman")
library(pacman)

# load all the packages you will use below 
p_load(
  dataverse, # data scraping
  DCPOtools, # analysis
  plm,
  glue, dotwhisker,
  huxtable, kableExtra, modelsummary, # tabulation
  latex2exp, patchwork, # visualization
  rstan, # Bayesian estimation
  tidyverse # data wrangling
) 

# Functions preload
set.seed(313)

parse_na_types <- function(s) {
    
    positions <- purrr::map(
        stringr::str_split(s, pattern = ""), 
        match,
        table = names(na_types_dict)
    ) %>%
        unlist()
    
    na_types_dict[positions] %>%
        unlist() %>%
        unname()
}

na_types_dict <- list("r" = NA_real_,
                      "i" = rlang::na_int,
                      "c" = NA_character_,
                      "l" = rlang::na_lgl)

as_glance_tibble <- function(..., na_types) {
    
    cols <- list(...)
    
    if (length(cols) != stringr::str_length(na_types)) {
        stop(
            "The number of columns provided does not match the number of ",
            "column types provided."
        )
    }
    
    na_types_long <- parse_na_types(na_types)
    
    entries <- purrr::map2(cols, 
                           na_types_long, 
                           function(.x, .y) {if (length(.x) == 0) .y else .x})
    
    tibble::as_tibble_row(entries)
    
}

tidy.pgmm <- function(x,
                      conf.int = FALSE,
                      conf.level = 0.95,
                      ...) {
    result <- summary(x)$coefficients %>%
        tibble::as_tibble(rownames = "term") %>%
        dplyr::rename(
            estimate = Estimate,
            std.error = `Std. Error`,
            statistic = `z-value`,
            p.value = `Pr(>|z|)`
        )
    
    if (conf.int) {
        ci <- confint(x, level = conf.level) %>% 
            as.data.frame() %>% 
            rownames_to_column(var = "term") %>% 
            dplyr::rename(
                conf.low = `2.5 %`,
                conf.high = `97.5 %`
            )
        result <- dplyr::left_join(result, ci, by = "term")
    }
    
    result
}


glance.pgmm <- function(x, ...) {
    s <- summary(x)
    as_glance_tibble(
        nobs = stats::nobs(x),
        n.country = pdim(x)$nT$n,
        na_types = "ii"
    )
}

glance.plm <- function(x, ...) {
    s <- summary(x)
    as_glance_tibble(
        nobs = stats::nobs(x),
        n.country = pdim(x)$nT$n,
        na_types = "ii"
    )
}

vcovBK_se <- function(x) {
  plm::vcovBK(x, cluster = "time") %>% 
    diag() %>% 
    sqrt()
}
```


## Claassen Replication

```{r claassen_replication_input, eval=FALSE}

# dcpo_input_raw <- DCPOtools::dcpo_setup(vars = read_csv(here::here("data-raw", "mood_dem.csv"),
#                                                         col_types = "cccccc"),
#                                         file = "data/dcpo_input_raw.csv")

dcpo_input_raw1 <- read_csv(here::here("data", "dcpo_input_raw.csv"), col_types = "cdcddcd") %>% 
  filter(!(str_detect(survey, "army_wvs") & # WVS obs identified as problematic by Claassen 
             ((country=="Albania" & year==1998) |
                (country=="Indonesia" & (year==2001 | year==2006)) |
                (country=="Iran" & year==2000) |
                (country=="Pakistan" & (year==1997 | year==2001)) | # 1996 in Claassen
                (country=="Vietnam" & year==2001)) |
             (str_detect(item, "strong_wvs") &
                ((country=="Egypt" & year==2012) |
                   (country=="Iran" & (year==2000 | year==2007)) | # 2005 in Claassen
                   (country=="India") |
                   (country=="Pakistan" & (year==1997 | year==2001)) | # 1996 in Claassen
                   (country=="Kyrgyzstan" & (year==2003 | year==2011)) |
                   (country=="Romania" & (year==1998 | year==2005 | year==2012)) |
                   (country=="Vietnam" & year==2001))) |
             (country %in% c("Puerto Rico", "Northern Ireland", 
                             "SrpSka Republic", "Hong Kong SAR China")))) %>%
  with_min_yrs(2)

# Note that before running `dataverse::get_file()` below, one should set their personal token and server in their system environment first: 
# Sys.setenv("DATAVERSE_KEY" = "exampleToken")
# Sys.setenv("DATAVERSE_SERVER" = "dataverse.harvard.edu")
# These values can be set to persist across R sessions using `usethis::edit_r_environ()`

if (!file.exists(here::here("data", "supdem raw survey marginals.tab"))) {
  tempfile <- dataverse::get_file("supdem raw survey marginals.tab", "doi:10.7910/DVN/HWLW0J") # AJPS replication file
  
  writeBin(tempfile, here::here("data", "supdem raw survey marginals.tab"))
}

supdem <- read_csv(here::here("data", "supdem raw survey marginals.tab"), col_types = "cdcddcdc")

supdem_cy <- supdem %>%                                             # 1390 obs
  janitor::clean_names() %>% 
  mutate(old_country = country,
         country = countrycode::countrycode(old_country, "country.name", "country.name")) %>%
  dplyr::select(country, year, project) %>% 
  unique()

claassen_input_cy <- read_csv(here::here("data", "dcpo_input_raw.csv"),
                              col_types = "cdcddcd") %>%           # 1864 obs
  mutate(p_dcpo = str_extract(survey, "^[a-z]+"), 
         project = case_when(p_dcpo == "afrob" ~ "afb",
                             p_dcpo == "amb" ~ "lapop",
                             p_dcpo == "arabb" ~ "arb",
                             p_dcpo == "asiab" ~ "asb",
                             p_dcpo == "asianb" ~ "asnb",
                             p_dcpo == "neb" ~ "ndb",
                             p_dcpo == "sasianb" ~ "sab",
                             TRUE ~ p_dcpo),
         y_dcpo = year) %>%
  dplyr::select(country, year, y_dcpo, survey, project) %>% 
  unique()

no_problems <- inner_join(supdem_cy, claassen_input_cy)             # 1298 obs

needed <- anti_join(supdem_cy, claassen_input_cy)                   # 93 obs

available <- anti_join(claassen_input_cy, supdem_cy)                # 566 obs

year_fixes <- left_join(needed, available, by = c("country", "project")) %>% # 89 obs
  mutate(diff = year.x - year.y) %>% 
  group_by(country, project, year.x) %>% 
  mutate(closest_to_claassen = min(abs(diff))) %>% 
  ungroup() %>% 
  group_by(country, project, year.y) %>% 
  mutate(closest_to_dcpo = min(abs(diff))) %>% 
  ungroup() %>% 
  filter(closest_to_claassen == abs(diff) & closest_to_dcpo == abs(diff) & abs(diff) <= 3) %>% 
  filter(!(country == "Egypt" & year.x == 2014 & survey == "afrob5")) # double match (it's really afrob6)

cys_crosswalk <- year_fixes %>% 
  select(country, y_dcpo, y_claassen = year.x, survey)

missing_cyps <- anti_join(needed, year_fixes,  by = c("country", "year" = "year.x", "project")) # 4 obs; listed in issue #5 

cys_to_drop <- anti_join(available, year_fixes, by = c("country", "year" = "year.y", "project")) %>% # 477 obs
  select(-y_dcpo)

claassen_replication_input_raw1 <- read_csv(here::here("data", "claassen_input_raw.csv"), col_types = "cdcddcd") %>% 
  filter(!(str_detect(item, "army_wvs") & # WVS obs identified as problematic by Claassen 
             ((country=="Albania" & year==1998) |
                (country=="Indonesia" & (year==2001 | year==2006)) |
                (country=="Iran" & year==2000) |
                (country=="Pakistan" & (year==1997 | year==2001)) | #in DCPO,it is 1997 instead of 1996
                (country=="Vietnam" & year==2001)) |
             (str_detect(item, "strong_wvs") &
                ((country=="Egypt" & year==2012) |
                   (country=="Iran" & (year==2000 | year==2007)) | #in DCPO, the year is 2007 rather than 2005
                   (country=="India") |
                   (country=="Pakistan" & (year==1997 | year==2001)) | #in DCPO,it is 1997 instead of 1996
                   (country=="Kyrgyzstan" & (year==2003 | year==2011)) |
                   (country=="Romania" & (year==1998 | year==2005 | year==2012)) |
                   (country=="Vietnam" & year==2001))))) %>% 
  anti_join(cys_to_drop, by = c("country", "year", "survey")) %>% # surveys unused by Claassen
  left_join(cys_crosswalk, by = c("country", "year" = "y_dcpo", "survey")) %>% 
  mutate(year = if_else(!is.na(y_claassen), y_claassen, year)) %>% # use Claassen's year codings
  mutate(item = if_else(item == "strong_amb_1" & year == 2004, "strong_amb_2", item)) %>% # items conflated in amb_combo file
  with_min_yrs(2)

claassen_replication_input <- DCPOtools::format_claassen(claassen_replication_input_raw1)
save(claassen_replication_input, file = here::here("data", "claassen_replication_input.rda"))
```

```{r claassen_m5, eval=FALSE}
load(here::here("data", "claassen_replication_input.rda"))

claassen_m5 <- rstan::stan(file = 'R/argon/dcpo_demsupport/R/supdem.stan.mod5.stan',
                           data = claassen_replication_input,
                           iter = 3000,
                           chains = 4,
                           cores = 4,
                           thin = 3,
                           pars = c("mu_lambda", "sigma_lambda", "sigma_delta", "sigma_theta", "phi", "lambda", "delta", "theta", "x_pred","log_lik"),
                           control = list(adapt_delta=0.99, stepsize=0.02, max_treedepth=11))

save(claassen_m5, file = load(here::here("data", "claassen_m5.rda")))
```




```{r ajps_mean}
load(here::here("data", "claassen_m5_3k_07-05-11-16.rda")) # our dataset of estimates, from surveys & DCPOtools, as generated in above (unrun) chunks

claassen_m5_theta <- rstan::extract(claassen_m5, pars = "theta") %>% 
  first()

ls_year <- 1988:2017
ls_country <- unique(claassen_input$data$country)

first_year <- min(claassen_input$data$year)

first_years <- claassen_input$data %>% 
  group_by(country) %>% 
  summarize(first_year = min(year))

sd_controls <- read_csv(here::here("data", "Support_democracy_ajps.csv"),
                        col_types = cols(.default = col_double(),
                                         Country = col_character(),
                                         Cnt_code = col_character(),
                                         ISO_code = col_character(),
                                         Region_UN = col_character())) %>% 
  mutate(country = countrycode::countrycode(as.character(Country), "country.name", "country.name"),
         year = as.numeric(as.character(Year)),
         regime = ifelse(Regime_VD > 1, 1, 0)) %>% 
  left_join(first_years, by = "country") %>% 
  filter(year >= first_year)

# standardize, exactly as in 'supdem stan estimation ajps.R' at L192
claassen_m5_theta_std = (claassen_m5_theta - mean(as.vector(claassen_m5_theta))) / sd(as.vector(claassen_m5_theta))

df_theta_mean <- purrr::map_df(1:1000, function(x) {
  claassen_m5_theta_std[x,,] %>% 
    as_tibble() %>% 
    rename_with(~ls_country, .cols = starts_with("V")) %>% 
    mutate(year = first_year + row_number() - 1) %>% 
    pivot_longer(cols = !year,
                 names_to = "country",
                 values_to = "theta") %>%
    arrange(country, year)
}) %>% 
  group_by(country, year) %>% 
  summarize(theta_mean = mean(theta)) %>% 
  right_join(sd_controls, by = c("country", "year")) %>% 
  plm::pdata.frame(index = c("country", "year"))

df_theta_mean %>% summarize(corr = cor(theta_mean, SupDem_trim))

corrs <- df_theta_mean %>%
    group_by(country) %>% 
    summarize(corr = cor(theta_mean, SupDem_trim))


ls_iv <- c("plm::lag(theta_mean, 1)",
           "plm::lag(SupDem_trim, 1)")
           #"plm::lag(SupDem_Democ, 1) + plm::lag(SupDem_Autoc, 1)")

ls_method <- c("plm", "pgmm")

ls_eq <- glue::glue("Libdem_VD ~ plm::lag(Libdem_VD, 1:2) + {ls_iv} + plm::lag(lnGDP_imp, 1) + plm::lag(GDP_imp_grth, 1) + plm::lag(Libdem_regUN, 1) + plm::lag(Pr_Muslim, 1) + plm::lag(Res_cp_WDI_di, 1)") 

ls_mod <- c(
  glue::glue("plm({ls_eq}, model = 'pooling', data = df_theta_mean)")# ,
  # glue(
  #   "pgmm({ls_eq} | plm::lag(Libdem_VD, 3:5), data = df_theta_mean, effect='individual', model='onestep', transformation='ld', indexes=c('Country', 'Year'))"
  # )
)

df_result_cls <- map(ls_mod, function(mod) {
  result <- eval(parse(text = mod))
})

tidy_cls <- map(df_result_cls, function(result) {
  df_result <- tidy(result, conf.int = TRUE)
  
  if (class(result)[[1]] == "plm") {
     mutate(df_result, std.error = vcovBK_se(result))
  } else {
    mutate(df_result, std.error = vcovHC_se(result))
  }
  
})

glance_cls <- map(df_result_cls, function(aResult) {
  if (class(aResult)[[1]] == "plm") { 
    glance.plm(aResult) # using the customized glance function
  } else {
    glance(aResult)
  }
})

result_cls <- map2(tidy_cls, glance_cls, ~ list(.x, .y))
#names(result_cls) <- c("pooled", "pooled-regime", "gmm", "gmm-regime")

ajps_mean_plot <- map_df(1:2, function(a) {
  result_cls[[a]][[1]] %>% 
    mutate(model = if_else(a==1, "Ours", "Claassen's"),
           term = str_replace(term, "SupDem_trim", "theta_mean")) %>% 
    filter(!str_detect(term, "(Intercept)"))
}) %>% 
  dotwhisker::dwplot() %>% 
  relabel_predictors(c(`plm::lag(Libdem_VD, 1:2)1` = "Democracy(t-1)",
                       `plm::lag(Libdem_VD, 1:2)2` = "Democracy(t-2)",
                       `plm::lag(theta_mean, 1)` = "Democratic Mood(t-1)",
                       `plm::lag(lnGDP_imp, 1)` = "Log GDP per capita(t-1)",
                       `plm::lag(GDP_imp_grth, 1)` = "GDP per capita Growth(t-1)",
                       `plm::lag(Libdem_regUN, 1)` = "Regional Democracy(t-1)",
                       `plm::lag(Pr_Muslim, 1)` = "Percent Muslim (t-1)", #there's a lag in the replication file
                       `plm::lag(Res_cp_WDI_di, 1)` = "Resource Dependence(t-1)")) +
  geom_vline(xintercept = 0, colour = "grey80", linetype = 2) +
  theme_minimal() +
  ggtitle("Dependent Variable: Level of Democracy") + 
  xlab("Coefficient Estimate") +
  scale_color_discrete(name="Dataset", breaks=c("Claassen's","Ours"))
```

```{r our_ajps_1k}
df_theta <- purrr::map(1:1000, function(x) {
  claassen_m5_theta_std[x,,] %>% 
    as_tibble() %>% 
    rename_with(~ls_country, .cols = starts_with("V")) %>% 
    mutate(year = first_year + row_number() - 1) %>% 
    pivot_longer(cols = !year,
                 names_to = "country",
                 values_to = "theta") %>%
    arrange(country, year) %>% 
    left_join(sd_controls, by = c("country", "year")) %>% 
    plm::pdata.frame(index = c("country", "year"))
})

result_m5_1k <- map(df_theta, function(aDataset) {
  plm(Libdem_VD ~ plm::lag(Libdem_VD, 1:2) + plm::lag(theta, 1) + plm::lag(lnGDP_imp, 1) +
        plm::lag(GDP_imp_grth, 1) + plm::lag(Libdem_regUN, 1) + plm::lag(Pr_Muslim, 1) +
        plm::lag(Res_cp_WDI_di, 1), model="pooling", data = aDataset)
})

result_betas_m5_1k <- mitools::MIextract(result_m5_1k, fun = coef)
result_vars_m5_1k <- mitools::MIextract(result_m5_1k, fun = vcovBK_se)

df_result_cls_1k <- summary(mitools::MIcombine(results = result_betas_m5_1k, 
                                               variance = result_vars_m5_1k)) %>%
  rownames_to_column(var = "term") %>% 
  rename(conf.low = `(lower`,
         conf.high = `upper)`, 
         estimate = results) %>% 
  filter(!str_detect(term, "(Intercept)")) %>% 
  mutate(model = "Ours")
```

```{r pure_claassen_ajps_1k}
load(here::here("data", "pure_claassen_1k_result.rda")) # from pure_claassen.R
# Replicate Claassen AJPS thetas, using his input data and his code
# light revision of 'supdem stan estimation ajps.R'

# options
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())

# read support for dem data
sddem1 = read.csv(here::here("data", "supdem raw survey marginals.tab"))

# remove NAs
sddem1 = sddem1[!sddem1$Response==0, ]

# create year by country indicators
year0 = 1987
sddem1 = sddem1[sddem1$Year > year0,]
sddem1 = unite(sddem1, YearCountry, c(Year, Country), sep = "_", remove = FALSE)

# create item by country indicators
sddem1 = unite(sddem1, ItemCnt, c(Item, Country), sep = "_", remove = FALSE)

# create year by project indicators
sddem1 = unite(sddem1, YrProj, c(Year, Project), sep = "_", remove = FALSE)

# create year by project by country indicators
sddem1 = unite(sddem1, YrProjCnt, c(YrProj, Country), sep = "_", remove = FALSE)

# factorise
sddem1$Country = as.factor(as.character(sddem1$Country))
sddem1$Item = as.factor(as.character(sddem1$Item))
sddem1$ItemCnt = as.factor(as.character(sddem1$ItemCnt))
sddem1$Project = as.factor(as.character(sddem1$Project))
sddem1$YrProj = as.factor(as.character(sddem1$YrProj))
sddem1$YrProjCnt = as.factor(as.character(sddem1$YrProjCnt))
sddem1$Year = sddem1$Year-year0

# count data
dim(sddem1)[1]                   # 3765 national responses
length(unique(sddem1$Country))   # 150 countries
length(unique(sddem1$Project))   # 14 projects
length(unique(sddem1$Item))      # 52 items
length(unique(sddem1$ItemCnt))   # 1453 item-country
length(unique(sddem1$YrProjCnt)) # 1390 national surveys
length(unique(sddem1$Year))      # 27 unique years (out of 30)
sum(sddem1$Sample) / dim(sddem1)[1] * length(unique(sddem1$YrProjCnt))   # 1,804,450 respondents              

# drop countries with less than 2 years of data
cnt.obs.years = rowSums(table(sddem1$Country, sddem1$Year) > 0)
sort(cnt.obs.years)
sddem2 = sddem1[sddem1$Country %in% levels(sddem1$Country)[cnt.obs.years > 1], ]
length(unique(sddem2$Country))   # 137 countries with 2+ years of data

#### Stan estimation
# prepare data for stan
n.items = length(unique(sddem2$Item))
n.cntrys = length(unique(sddem2$Country))
n.yrs = 2017-year0
n.proj = length(unique(sddem2$Project))
n.resp = dim(sddem2)[1]
n.itm.cnt = length(unique(sddem2$ItemCnt))
n.cntry.yrs = n.cntrys * n.yrs
n.yr.proj.cnt = length(unique(sddem2$YrProjCnt))
cntrys = as.numeric(factor(sddem2$Country))
cnt.names = as.character(sort(unique(sddem2$Country)))
cnt.code = as.character(sddem2[match(cnt.names, sddem2$Country), "CAbb"])
cnt.code[83] = "MNE"
cnt.code[106] = "SRB"
items = as.numeric(factor(sddem2$Item))
yrs = sddem2$Year
projs = as.numeric(factor(sddem2$Project))
itm.cnts = as.numeric(factor(sddem2$ItemCnt))

# specify data for stan
dat.2 = list(N=n.resp, K=n.items, T=n.yrs, J=n.cntrys, P=n.itm.cnt, jj=cntrys, tt=yrs, 
             pp=itm.cnts, kk=items, x=sddem2$Response, samp=sddem2$Sample)
sapply(dat.2, summary)

# pars
pars.5 = c("mu_lambda","sigma_lambda","sigma_delta","sigma_theta","phi","lambda","delta","theta",
           "x_pred","log_lik")

save(dat.2, pars.5, file = here::here("R", "argon", "dcpo_demsupport_rep", "data", "pure_claassen.rda"))

# run 'R/argon/dcpo_demsupport_rep/R/pure_claassen_m5.R'
stan.mod.5 <- rio::import(here::here("R", "argon", "dcpo_demsupport_rep", "data", "pure_claassen_m5.rda"))

#### Extract theta estimates

theta.out = rstan::extract(stan.mod.5, pars = c("theta"))[[1]]
theta.std = (theta.out - mean(as.vector(theta.out))) / sd(as.vector(theta.out)) # standardize
theta.out.t = apply( theta.std, 1, function(x) t(x) )
theta.out.df = data.frame(Country=rep(cnt.names, length.out=n.cntrys*30), 
                          ISO_code=rep(cnt.code, length.out=n.cntrys*30),
                          Year=rep(1988:2017, each=n.cntrys), theta.out.t)
theta.pe = theta.out.df[,1:3]
theta.dim = dim(theta.out.df)[2]
theta.pe$SupDem_trim = apply(theta.out.df[,4:theta.dim], 1, mean)

first.yr = data.frame(Country=levels(sddem2$Country),
                      First_yr = as.vector(by(sddem2, sddem2$Country, function(x) min(as.numeric(x$Year))+1987)))

theta.pe = merge(theta.pe, first.yr, by="Country", all.x=TRUE)
cnts = theta.pe[theta.pe$Year==2008, "Country"]
frst.yr = theta.pe[theta.pe$Year==2008, "First_yr"]
for(i in 1:length(cnts)) {
    theta.pe[theta.pe$Country==cnts[i] & theta.pe$Year<frst.yr[i], "SupDem_trim"] = NA
}

sd_controls <- read_csv(here::here("data", "Support_democracy_ajps.csv"),
                        col_types = cols(.default = col_double(),
                                         Country = col_character(),
                                         Cnt_code = col_character(),
                                         ISO_code = col_character(),
                                         Region_UN = col_character()))


theta.out.df_list <- map(1:1000, function(x) {
    theta.pe %>% 
        mutate(theta0 = theta.out.t[,x],
               theta = if_else(!is.na(SupDem_trim), theta0, NA_real_)) %>% 
        left_join(sd_controls, by = c("Country", "Year")) %>% 
        plm::pdata.frame(index = c("Country", "Year"))
})

mod.1_1k <- map(theta.out.df_list, function(aDataset) {
    plm(Libdem_VD ~ plm::lag(Libdem_VD, 1:2) + plm::lag(theta, 1) + plm::lag(lnGDP_imp, 1) +
            plm::lag(GDP_imp_grth, 1) + plm::lag(Libdem_regUN, 1) + plm::lag(Pr_Muslim, 1) +
            plm::lag(Res_cp_WDI_di, 1), model="pooling", data = aDataset)
})

result_betas_mod.1_1k <- mitools::MIextract(mod.1_1k, fun = coef)
result_vars_mod.1_1k <- mitools::MIextract(mod.1_1k, fun = vcovBK_se)

mod.1_df_result_cls_1k <- summary(mitools::MIcombine(results = result_betas_mod.1_1k,
                                            variance = result_vars_mod.1_1k)) %>%
    rownames_to_column(var = "term") %>% 
    rename(conf.low = `(lower`,
           conf.high = `upper)`, 
           estimate = results) %>% 
    filter(!str_detect(term, "(Intercept)")) %>% 
    mutate(model = "Claassen's")
```

```{r ajps_1k_plot}
ajps_1k_plot <- bind_rows(df_result_cls_1k, mod.1_df_result_cls_1k) %>% 
  dotwhisker::dwplot() %>% 
  relabel_predictors(c(`plm::lag(Libdem_VD, 1:2)1` = "Democracy(t-1)",
                       `plm::lag(Libdem_VD, 1:2)2` = "Democracy(t-2)",
                       `plm::lag(theta, 1)` = "Democratic Mood(t-1)",
                       `plm::lag(lnGDP_imp, 1)` = "Log GDP per capita(t-1)",
                       `plm::lag(GDP_imp_grth, 1)` = "GDP per capita Growth(t-1)",
                       `plm::lag(Libdem_regUN, 1)` = "Regional Democracy(t-1)",
                       `plm::lag(Pr_Muslim, 1)` = "Percent Muslim (t-1)", #there's a lag in the replication file
                       `plm::lag(Res_cp_WDI_di, 1)` = "Resource Dependence(t-1)")) +
  geom_vline(xintercept = 0, colour = "grey80", linetype = 2) +
  theme_minimal() +
  ggtitle("Dependent Variable: Level of Democracy") + 
  xlab("Coefficient Estimate") +
  scale_color_discrete(name="1k Samples\nDataset", breaks=c("Claassen's","Ours"))
```



```{r apsr_mean}
if (!file.exists(here::here("data", "dem_mood_apsr.csv"))) {
  tempfile <- dataverse::get_file("dem_mood_apsr.tab", "doi:10.7910/DVN/FECIO3", 
                                  format = "original") # Claassen's APSR replication file
  
  writeBin(tempfile, here::here("data", "dem_mood_apsr.csv"))
}

sd_controls_apsr <- read_csv(here::here("data", "dem_mood_apsr.csv"), 
                        col_types = cols(.default = col_double(),
                                         Country = col_character(),
                                         ISO_code = col_character(),
                                         Region_UN = col_character())) %>% 
  mutate(country = countrycode::countrycode(as.character(Country), "country.name", "country.name"),
         year = as.numeric(as.character(Year))) %>% 
  left_join(first_years, by = "country") %>% 
  filter(year >= first_year)

df_theta_mean_apsr <- purrr::map_df(1:1000, function(x) {
  claassen_m5_theta_std[x,,] %>% 
    as_tibble() %>% 
    rename_with(~ls_country, .cols = starts_with("V")) %>% 
    mutate(year = first_year + row_number() - 1) %>% 
    pivot_longer(cols = !year,
                 names_to = "country",
                 values_to = "theta") %>%
    arrange(country, year)
}) %>% 
  group_by(country, year) %>% 
  summarize(theta_mean = mean(theta)) %>% 
  right_join(sd_controls_apsr, by = c("country", "year")) %>% 
  plm::pdata.frame(index = c("country", "year"))

cor(df_theta_mean$theta_mean, df_theta_mean_apsr$theta_mean) # 1

ls_dv_apsr <- c("theta_mean", "SupDem_trim")

ls_eq_apsr <- glue::glue("diff({ls_dv_apsr}, lag=1) ~ plm::lag({ls_dv_apsr}, 1:2) + diff(Libdem_z, lag=1) + plm::lag(Libdem_z, 1) + diff(lnGDP_imp, lag=1) + plm::lag(lnGDP_imp, 1)")

ls_mod_apsr <- glue::glue("plm({ls_eq_apsr}, model = 'pooling', data = df_theta_mean_apsr)")

df_result_cls_apsr <- map(ls_mod_apsr, function(mod) {
  result <- eval(parse(text = mod))
})

tidy_cls_apsr <- map(df_result_cls_apsr, function(result) {
  df_result <- tidy(result, conf.int = TRUE)
  
  if (class(result)[[1]] == "plm") {
     mutate(df_result, std.error = vcovBK_se(result))
  } else {
    mutate(df_result, std.error = vcovHC_se(result))
  }
})

glance_cls_apsr <- map(df_result_cls_apsr, function(aResult) {
  if (class(aResult)[[1]] == "plm") { 
    glance.plm(aResult) # using the customized glance function
  } else {
    glance(aResult)
  }
})

result_cls_apsr <- map2(tidy_cls_apsr, glance_cls_apsr, ~ list(.x, .y))
#names(result_cls) <- c("pooled", "pooled-regime", "gmm", "gmm-regime")

apsr_mean_plot <- map_df(1:2, function(a) {
  result_cls_apsr[[a]][[1]] %>% 
    mutate(model = if_else(a==1, "Ours", "Claassen's")) %>% 
    filter(!str_detect(term, "(Intercept)"))
}) %>% 
  dotwhisker::dwplot() %>% 
  relabel_predictors(c(`plm::lag(theta_mean, 1:2)1` = "Support[t-1]",
                       `plm::lag(theta_mean, 1:2)2` = "Support[t-2]",
                       `plm::lag(SupDem_trim, 1:2)1` = "Support[t-1]",
                       `plm::lag(SupDem_trim, 1:2)2` = "Support[t-2]",
                       `diff(Libdem_z, lag = 1)` = "Delta~Liberal~democracy",
                       `plm::lag(Libdem_z, 1)` = "Liberal~democracy[t-1]",
                       `diff(lnGDP_imp, lag = 1)` = "Delta~Log GDP per capita",
                       `plm::lag(lnGDP_imp, 1)` = "Log GDP per capita[t-1]")) +
  geom_vline(xintercept = 0, colour = "grey80", linetype = 2) +
  theme_minimal() +
  ggtitle("Dependent Variable: Delta Support for Democracy") + 
  xlab("Coefficient Estimate") +
  scale_color_discrete(name="Dataset", breaks=c("Claassen's","Ours"))
```

```{r apsr_1k}
df_theta_apsr <- purrr::map(1:1000, function(x) {
  claassen_m5_theta_std[x,,] %>% 
    as_tibble() %>% 
    rename_with(~ls_country, .cols = starts_with("V")) %>% 
    mutate(year = first_year + row_number() - 1) %>% 
    pivot_longer(cols = !year,
                 names_to = "country",
                 values_to = "theta") %>%
    arrange(country, year) %>% 
    left_join(sd_controls_apsr, by = c("country", "year")) %>% 
    plm::pdata.frame(index = c("country", "year"))
})

result_m5_1k_apsr <- map(df_theta_apsr, function(aDataset) {
  plm(diff(theta, lag=1) ~ plm::lag(theta, 1:2) + diff(Libdem_z, lag=1) 
           + plm::lag(Libdem_z, 1) + diff(lnGDP_imp, lag=1) + plm::lag(lnGDP_imp, 1), 
           aDataset, model="pooling")
})

result_betas_m5_1k_apsr <- mitools::MIextract(result_m5_1k_apsr, fun = coef)
result_vars_m5_1k_apsr <- mitools::MIextract(result_m5_1k_apsr, fun = vcovBK_se)

df_result_cls_1k_apsr <- summary(mitools::MIcombine(results = result_betas_m5_1k_apsr, 
                                                    variance = result_vars_m5_1k_apsr)) %>%
  rownames_to_column(var = "term") %>% 
  rename(conf.low = `(lower`,
         conf.high = `upper)`, 
         estimate = results) %>% 
  filter(!str_detect(term, "(Intercept)")) %>% 
  mutate(model = "Ours")
```

```{r pure_claassen_apsr_1k}
sd.apsr = read.csv(here::here("data", "dem_mood_apsr.csv")) %>% 
    select(-starts_with("SupDem"))

theta.out.df_list_apsr <- map(1:1000, function(x) {
    theta.pe %>% 
        mutate(theta0 = theta.out.t[,x],
               theta = if_else(!is.na(SupDem_trim), theta0, NA_real_)) %>% 
        left_join(sd.apsr, by = c("Country", "Year")) %>% 
        plm::pdata.frame(index = c("Country", "Year"))
})

mod.1_apsr_1k <- map(theta.out.df_list_apsr, function(aDataset) {
    plm(diff(theta, lag=1) ~ plm::lag(theta, 1:2) + diff(Libdem_z, lag=1) 
        + plm::lag(Libdem_z, 1) + diff(lnGDP_imp, lag=1) + plm::lag(lnGDP_imp, 1), 
        data = aDataset, model="pooling")
})

result_betas_mod.1_apsr_1k <- mitools::MIextract(mod.1_apsr_1k, fun = coef)
result_vars_mod.1_apsr_1k <- mitools::MIextract(mod.1_apsr_1k, fun = vcovBK_se)

mod.1_df_result_cls_apsr_1k <- summary(mitools::MIcombine(results = result_betas_mod.1_apsr_1k,
                                                     variance = result_vars_mod.1_apsr_1k)) %>%
    rownames_to_column(var = "term") %>% 
    rename(conf.low = `(lower`,
           conf.high = `upper)`, 
           estimate = results) %>% 
    filter(!str_detect(term, "(Intercept)")) %>% 
    mutate(model = "Claassen's")
```

```{r apsr_1k_plot}
apsr_1k_plot <- bind_rows(df_result_cls_1k_apsr, mod.1_df_result_cls_apsr_1k) %>% 
  dotwhisker::dwplot() %>% 
  relabel_predictors(c(
    `plm::lag(SupDem_trim, 1:2)1` = "Support[t-1]",
    `plm::lag(SupDem_trim, 1:2)2` = "Support[t-2]",
    `plm::lag(theta, 1:2)1` = "Support[t-1]",
    `plm::lag(theta, 1:2)2` = "Support[t-2]",
    `diff(Liberal_z, lag = 1)` = "Delta~Support(demo~only)",
    `diff(Vdem_liberal_z, lag = 1)` = "Delta~Support(demo~only)",
    `plm::lag(Liberal_z, 1)` = "Support[t-1](demo~only)",
    `plm::lag(Vdem_liberal_z, 1)` = "Support[t-1](demo~only)",
    `diff(Polyarchy_z, lag = 1)` = "Delta~Support(auto~only)",
    `diff(Vdem_polyarchy_z, lag = 1)` = "Delta~Support(auto~only)",
    `plm::lag(Polyarchy_z, 1)` = "Support[t-1](auto~only)",
    `plm::lag(Vdem_polyarchy_z, 1)` = "Support[t-1](auto~only)",
    `diff(Libdem_z, lag = 1)` = "Delta~Liberal~democracy",
    `diff(Vdem_libdem_z, lag = 1)` = "Delta~Liberal~democracy",
    `plm::lag(Libdem_z, 1)` = "Liberal~democracy[t-1]",
    `plm::lag(Vdem_libdem_z, 1)` = "Liberal~democracy[t-1]",
    `diff(lnGDP_imp, lag = 1)` = "Delta~Log~GDP~per~capita",
    `diff(lg_imp_mdpgdp, lag = 1)` = "Delta~Log~GDP~per~capita",
    `plm::lag(lnGDP_imp, 1)` = "Log~GDP[t-1]",
    `plm::lag(lg_imp_mdpgdp, 1)` = "Log~GDP[t-1]"
)) +
  geom_vline(xintercept = 0, colour = "grey80", linetype = 2) +
  theme_minimal() +
  ggtitle("Dependent Variable: Delta Support for Democracy") + 
  xlab("Coefficient Estimate") +
  scale_color_discrete(name="1k Samples\nDataset", breaks=c("Claassen's","Ours"))

```

```{r results_comparison_plots, include=TRUE, fig.width=7}
ajps_mean_plot 
ajps_1k_plot
apsr_mean_plot
apsr_1k_plot

```

```{r expanded_claassen_ajps}
# these are estimates based on Claassen's original dataset, plus all additional country-year-item observations we found; see 

load(here::here("data", "exp_claassen_m5_3k_06-13-17-09.rda")) #  dataset of estimates, based on Claassen's original dataset, plus all additional country-year-item observations we found, as generated in (at the moment) expanded_claassen_input.R

exp_claassen_m5_theta <- rstan::extract(exp_claassen_m5, pars = "theta") %>% 
  first()

ls_ec_year <- min(expanded_claassen_input$data$year):max(expanded_claassen_input$data$year)
ls_ec_country <- unique(expanded_claassen_input$data$country)

ec_first_year <- min(expanded_claassen_input$data$year)

ec_controls <- read_csv(here::here("data", "control_variables_ajps.csv"),
                        col_types = cols(.default = col_double(),
                                         country = col_character(),
                                         ISO = col_character(),
                                         Region_UN = col_character(),
                                         regime = col_logical())) %>% 
  mutate(country = countrycode::countrycode(as.character(country), "country.name", "country.name"),
         year = as.numeric(as.character(year))) %>% 
  filter(year >= first_year)

# standardize, exactly as in 'supdem stan estimation ajps.R' at L192 (= for assignment and all)
exp_claassen_m5_theta_std = (exp_claassen_m5_theta - mean(as.vector(exp_claassen_m5_theta))) / sd(as.vector(exp_claassen_m5_theta))

ec_df_theta <- purrr::map(1:1000, function(x) {
  exp_claassen_m5_theta_std[x,,] %>% 
    as_tibble() %>% 
    rename_with(~ls_ec_country, .cols = starts_with("V")) %>% 
    mutate(year = ec_first_year + row_number() - 1) %>% 
    pivot_longer(cols = !year,
                 names_to = "country",
                 values_to = "theta") %>%
    arrange(country, year) %>% 
    left_join(ec_controls, by = c("country", "year")) %>% 
    plm::pdata.frame(index = c("country", "year"))
})

ec_result_m5_1k <- map(ec_df_theta, function(aDataset) {
  plm::plm(Vdem_libdem ~ plm::lag(Vdem_libdem, 1:2) + plm::lag(theta, 1) + plm::lag(lg_imp_mdpgdp, 1) + plm::lag(mdprgdp_grwth, 1) + plm::lag(Region_libdem, 1) + plm::lag(muslism_prop_2010, 1) + plm::lag(dependence_pc_di, 1), model="pooling", data = aDataset)
})

ec_result_betas_m5_1k <- mitools::MIextract(ec_result_m5_1k, fun = coef)
ec_result_vars_m5_1k <- mitools::MIextract(ec_result_m5_1k, fun = vcovBK_se)

ec_df_result_cls_1k <- summary(mitools::MIcombine(results = ec_result_betas_m5_1k, 
                                               variance = ec_result_vars_m5_1k)) %>%
  rownames_to_column(var = "term") %>% 
  rename(conf.low = `(lower`,
         conf.high = `upper)`, 
         estimate = results) %>% 
  filter(!str_detect(term, "(Intercept)"))
```

```{r all_claassen_res_ajps_plot, include=TRUE, fig.width=7}
all_claassen_res_ajps <- ec_df_result_cls_1k %>% 
              mutate(model = "Expanded Dataset\nw/ Uncertainty") %>% 
  bind_rows(mod.1_df_result_cls_1k %>% 
              mutate(model = "Claassen w/ Uncertainty")) %>% 
  bind_rows(result_cls[[2]][[1]] %>% 
    mutate(model = "Claassen 2020a",
           term = str_replace(term, "SupDem_trim", "theta_mean"))) %>% 
  filter(!str_detect(term, "(Intercept)"))

all_claassen_res_ajps_plot <- dotwhisker::dwplot(all_claassen_res_ajps) %>% 
  relabel_predictors(c(
    `plm::lag(Libdem_VD, 1:2)1` = "Democracy[t-1]",
    `plm::lag(Libdem_VD, 1:2)2` = "Democracy[t-2]",
    `plm::lag(Vdem_libdem, 1:2)1` = "Democracy[t-1]",
    `plm::lag(Vdem_libdem, 1:2)2` = "Democracy[t-2]",
    `plm::lag(theta_mean, 1)` = "Support[t-1]",
    `plm::lag(theta, 1)` = "Support[t-1]",
    `plm::lag(SupDem_Democ, 1)` = "Support[t-1](demo~only)",
    `plm::lag(SupDem_Autoc, 1)` = "Support[t-1](auto~only)",
    `plm::lag(theta_dem_trim, 1)` = "Support[t-1](demo~only)",
    `plm::lag(theta_aut_trim, 1)` = "Support[t-1](auto~only)",
    `plm::lag(lnGDP_imp, 1)` = "Log~GDP~per~capita[t-1]",
    `plm::lag(lg_imp_mdpgdp, 1)` = "Log~GDP~per~capita[t-1]",
    `plm::lag(GDP_imp_grth, 1)` = "GDP~per~capita~growth[t-1]",
    `plm::lag(mdprgdp_grwth, 1)` = "GDP~per~capita~growth[t-1]",
    `plm::lag(Libdem_regUN, 1)` = "Regional~democracy[t-1]",
    `plm::lag(Region_libdem, 1)` = "Regional~democracy[t-1]",
    `plm::lag(Pr_Muslim, 1)` = "Percent~Muslim[t-1]",
    `plm::lag(muslism_prop_2010, 1)` = "Percent~Muslim[t-1]",
    `plm::lag(Res_cp_WDI_di, 1)` = "Resource~dependence[t-1]",
    `plm::lag(dependence_pc_di, 1)` = "Resource~dependence[t-1]"
  )
  ) +
  geom_vline(xintercept = 0, colour = "grey80", linetype = 2) +
  theme_minimal() +
  ggtitle("Dependent Variable: Level of Democracy") + 
  xlab("Coefficient Estimate") +
  scale_color_discrete(name="Dataset", guide = guide_legend(reverse = TRUE))

all_claassen_res_ajps_plot
```

```{r expanded_claassen_apsr}
ec_df_theta_apsr <- purrr::map(1:1000, function(x) {
  exp_claassen_m5_theta_std[x,,] %>% 
    as_tibble() %>% 
    rename_with(~ls_ec_country, .cols = starts_with("V")) %>% 
    mutate(year = ec_first_year + row_number() - 1) %>% 
    pivot_longer(cols = !year,
                 names_to = "country",
                 values_to = "theta") %>%
    arrange(country, year) %>% 
    left_join(sd_controls_apsr, by = c("country", "year")) %>% 
    plm::pdata.frame(index = c("country", "year"))
})

ec_result_m5_1k_apsr <- map(ec_df_theta_apsr, function(aDataset) {
  plm(diff(theta, lag=1) ~ plm::lag(theta, 1:2) + diff(Libdem_z, lag=1) 
           + plm::lag(Libdem_z, 1) + diff(lnGDP_imp, lag=1) + plm::lag(lnGDP_imp, 1), 
           aDataset, model="pooling")
})

ec_result_betas_m5_1k_apsr <- mitools::MIextract(ec_result_m5_1k_apsr, fun = coef)
ec_result_vars_m5_1k_apsr <- mitools::MIextract(ec_result_m5_1k_apsr, fun = vcovBK_se)

ec_df_result_cls_1k_apsr <- summary(mitools::MIcombine(results = ec_result_betas_m5_1k_apsr, 
                                                    variance = ec_result_vars_m5_1k_apsr)) %>%
  rownames_to_column(var = "term") %>% 
  rename(conf.low = `(lower`,
         conf.high = `upper)`, 
         estimate = results) %>% 
  filter(!str_detect(term, "(Intercept)"))
```




\pagebreak
